github.com:
    users:
        2freemanall:
            oauth_token: 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
            git_protocol: https
    git_protocol: https
    oauth_token: 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
    user: 2freemanall
